---
- name: "Install common tools"
  hosts: all
  
  tasks:
    - name: Install nodejs
      import_role:
        name: nodejs
      ignore_errors: yes
      tags: nodejs

    - name: Install python
      import_role:
        name: python
      ignore_errors: yes
      tags: python

    - name: Install go
      import_role:
        name: go
      ignore_errors: yes
      tags: go
