---
- name: "Install common tools"
  hosts: all
  
  tasks:
    - name: Install nodejs
      win_chocolatey:
        name: nodejs-lts
        state: present
      ignore_errors: yes
      tags: nodejs


    - name: Install python
      win_chocolatey:
        name: python
        state: present
      ignore_errors: yes
      tags: python

    - name: Install go
      win_chocolatey:
        name: go
        state: present
      ignore_errors: yes
      tags: go
