---
- name: "Install other utilities"
  hosts: all
  
  tasks:

    - name: Install windirstat
      win_chocolatey:
        name: windirstat
        state: present

    - name: Install filezilla
      win_chocolatey:
        name: filezilla
        state: present
