---
- name: "Install other utilities"
  hosts: all
  
  tasks:

    - name: Install windirstat
      win_chocolatey:
        name: windirstat
        state: present
      ignore_errors: yes

    - name: Install filezilla
      win_chocolatey:
        name: filezilla
        state: present
      ignore_errors: yes
