---
- name: "Install terminal utilities"
  hosts: all
  
  tasks:
    - name: Create tools directory structure
      win_file:
        path: C:\Tools
        state: directory

    - name: Ensure that tools is in path
      win_path:
        elements:
        - 'C:\Tools'

    - name: Install 7-zip
      win_chocolatey:
        name: 7zip.install
        state: present
      ignore_errors: yes
        
    - name: Install jq
      win_chocolatey:
        name: jq
        state: present
      ignore_errors: yes
        
    - name: Install yq
      win_chocolatey:
        name: yq
        state: present
      ignore_errors: yes
        
    - name: Install curl
      win_chocolatey:
        name: curl
        state: present
      ignore_errors: yes
        
    - name: Install bind-tools, dig
      win_chocolatey:
        name: bind-toolsonly
        state: present
      ignore_errors: yes
        
    - name: Install git
      win_chocolatey:
        name: git
        state: present
      ignore_errors: yes

    - name: Install lazygit
      win_chocolatey:
        name: lazygit
        state: present
      ignore_errors: yes

    - name: Install vifm - terminal file manager
      win_chocolatey:
        name: git
        state: present
      ignore_errors: yes
        
    - name: Install ripgrep
      win_chocolatey:
        name: ripgrep
        state: present
      ignore_errors: yes

    - name: Install sysinternals
      win_chocolatey:
        name: sysinternals
        state: present
        params: '/InstallDir:C:\Tools\sysinternals'
      ignore_errors: yes

    - name: Ensure that sysinternals is in path
      win_path:
        elements:
        - 'C:\Tools\sysinternals'

    - name: Install rimraf - fast directory remover
      win_command: npm install rimraf -g
      ignore_errors: yes
        
