---
- name: "Install terminal utilities"
  hosts: all
  
  tasks:
    - name: Create tools directory structure
      win_file:
        path: C:\Tools
        state: directory

    - name: Ensure that tools is in path
      win_path:
        elements:
        - 'C:\Tools'

    - name: Install 7-zip
      win_chocolatey:
        name: 7zip.install
        state: present
        
    - name: Install jq
      win_chocolatey:
        name: jq
        state: present
        
    - name: Install curl
      win_chocolatey:
        name: curl
        state: present
        
    - name: Install git
      win_chocolatey:
        name: git
        state: present

    - name: Install vifm
      win_chocolatey:
        name: git
        state: present
        
    - name: Install ripgrep
      win_chocolatey:
        name: ripgrep
        state: present

    - name: Install sysinternals
      win_chocolatey:
        name: sysinternals
        state: present
        params: '/InstallDir:C:\Tools\sysinternals'

    - name: Ensure that sysinternals is in path
      win_path:
        elements:
        - 'C:\Tools\sysinternals'

    - name: Install rimraf
      win_command: npm install rimraf -g
        