---
- name: "Install terminal utilities"
  hosts: all
  
  tasks:
    - name: Create tools directory structure
      win_file:
        path: C:\Tools
        state: directory

    - name: Install 7-zip
      win_chocolatey:
        name: 7zip.install
        state: present
        
    - name: Install jq
      win_chocolatey:
        name: jq
        state: present
        
    - name: Install curl
      win_chocolatey:
        name: curl
        state: present
        
    - name: Install git
      win_chocolatey:
        name: git
        state: present

    - name: Install vifm
      win_chocolatey:
        name: git
        state: present