- name : Install all linux tools
  hosts: all

# Common: nodejs, go, python
- import_playbook: linux/common.yml

# Utilities without GUI
- import_playbook: linux/vim.yml
- import_playbook: linux/utilities.yml
- import_playbook: linux/container.yml

# Desktop tools
- import_playbook: linux/desktop.yml
- import_playbook: linux/vm.yml
