- name : Install all linux tools
  hosts: all
  become: yes
  tasks:
    - name: Install nodejs
      import_role:
        name: geerlingguy.nodejs

- import_playbook: linux/vim.yml
- import_playbook: linux/utilities.yml
- import_playbook: linux/container.yml


# Desktop tools
- import_playbook: linux/desktop.yml
- import_playbook: linux/vm.yml
