---
- name: "Install desktop tools"
  hosts: all
  
  tasks:
    - name: "Add darktable ppa"
      become: yes
      apt_repository:
        repo: ppa:ubuntuhandbook1/darktable

    - name: "Add gimp ppa"
      become: yes
      apt_repository:
        repo: ppa:otto-kesselgulasch/gimp        

    - name: "Add peek ppa"
      become: yes
      apt_repository:
        repo: ppa:peek-developers/stable

    - name: "Install various dekstop tools"
      become: yes
      apt: name= {{ item }} update_cache=yes state=latest
      with_items:
        # note taking 
        - cherrytree
        # screenshot
        - shutter
        # audio player
        - audacious
        # launcher
        - synapse
        # dock
        - plank
        # raw image processor
        - darktable
        # bitmap image processor
        - gimp
        # meld comparator
        - meld
        # glogg  log viewer
        - glogg
        # peek gif recorder
        - peek
        
    - name: Install vscode
      become: yes
      import_role:
        name: gantsign.visual-studio-code