---
- name: "Install desktop tools"
  hosts: all
  
  tasks:
    - name: "Add darktable ppa"
      become: yes
      apt_repository:
        repo: ppa:ubuntuhandbook1/darktable
      ignore_errors: yes

    - name: "Add cherrytree ppa"
      become: yes
      apt_repository:
        repo: ppa:giuspen/ppa
      ignore_errors: yes

    - name: "App appimage launcher"
      become: yes
      apt_repository:
        repo: ppa:appimagelauncher-team/stable
      ignore_errors: yes

    - name: "Add gimp ppa"
      become: yes
      apt_repository:
        repo: ppa:otto-kesselgulasch/gimp        
      ignore_errors: yes

    - name: "Add peek ppa"
      become: yes
      apt_repository:
        repo: ppa:peek-developers/stable
      ignore_errors: yes

    - name: "Add shutter ppa"
      become: yes
      apt_repository:
        repo: ppa:linuxuprising/shutter
      ignore_errors: yes

    - name: "Install cherrytree note taking"
      become: yes
      apt: name=cherrytree update_cache=yes state=latest
      ignore_errors: yes

    - name: "Install shutter screenshot tool"
      become: yes
      apt: name=shutter update_cache=yes state=latest
      ignore_errors: yes

    - name: "Install audacious audio player"
      become: yes
      apt: name=audacious update_cache=yes state=latest
      ignore_errors: yes

    - name: "Install synapse launcher"
      become: yes
      apt: name=synapse update_cache=yes state=latest
      ignore_errors: yes

    - name: "Install plank dock"
      become: yes
      apt: name=plank update_cache=yes state=latest
      ignore_errors: yes

    - name: "Install darktable"
      become: yes
      apt: name=darktable update_cache=yes state=latest
      ignore_errors: yes

    - name: "Install gimp"
      become: yes
      apt: name=gimp update_cache=yes state=latest
      ignore_errors: yes

    - name: "Install meld file comparator"
      become: yes
      apt: name=meld update_cache=yes state=latest
      ignore_errors: yes

    - name: "Install glogg log viewer"
      become: yes
      apt: name=glogg update_cache=yes state=latest
      ignore_errors: yes

    - name: "Install peek"
      become: yes
      apt: name=peek update_cache=yes state=latest
      ignore_errors: yes
        
    - name: "Install appimage launcher"
      become: yes
      apt: name=appimagelauncher update_cache=yes state=latest
      ignore_errors: yes

    - name: Install vscode
      become: yes
      import_role:
        name: gantsign.visual-studio-code
      ignore_errors: yes
