---
- name: "Install devops tools"
  hosts: all
  
  tasks:
    - name: Install docker
      become: yes
      import_role:
        name: geerlingguy.docker
      ignore_errors: yes
      tags: docker 

    - stat:
        path: /usr/local/bin/kubectl
      register: kubectl_file  
      tags: kubectl

    - name: Install kubectl
      become: yes
      shell: | 
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
      when: kubectl_file.stat.exists == false
      ignore_errors: yes
      tags: kubectl

    - stat:
        path: /usr/local/bin/kubectx
      register: kubectx_file  
      tags: kubectl

    - name: Download kubectx, kubectl
      become: yes
      git: repo=https://github.com/ahmetb/kubectx dest=/opt/kubectx version=master
      ignore_errors: yes
      when: kubectx_file.stat.exists == false
      tags: kubectl

    - name: Install kubectx and kubens
      become: yes
      shell: | 
        sudo ln -s /opt/kubectx/kubectx /usr/local/bin/kubectx
        sudo ln -s /opt/kubectx/kubens /usr/local/bin/kubens
      when: kubectx_file.stat.exists == false
      ignore_errors: yes
      tags: kubectl

    # Go utilities
    - name: check go version
      command: go version
      register: go_result
      changed_when: no
      ignore_errors: true
      tags: lazydocker

    - set_fact:
        go_path: "{{ lookup('env', 'GOPATH') | default(ansible_env.HOME+'/go', true) }}"
      when: not go_result is failed
      tags: lazydocker


    - name: "Install lazydocker"
      shell: go get -u github.com/jesseduffield/lazydocker
      environment:
        GOPATH: "{{ go_path }}"
      when: not go_result is failed
      ignore_errors: yes
      tags: lazydocker

    - name: Install k9s
      import_role:
        name: k9s
      ignore_errors: yes
      tags: k9s

    - stat:
        path: /usr/local/bin/stern
      register: stern_file  
      tags: stern

    - name: "Download and install stern"
      shell: | 
        curl -LO https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64
        chmod +x ./stern_linux_amd64
        sudo mv ./stern_linux_amd64 /usr/local/bin/stern
      when: stern_file.stat.exists == false
      ignore_errors: yes
      tags: stern
