---
- name: "Install terminal utilities"
  hosts: all
  
  tasks:
    - name: "Install rename, jq, ncdu "
      become: yes
      apt: name= {{ item }} update_cache=yes state=latest
      with_items:
        # renaming multiple files
        - rename
        # json manipulation
        - jq
        # disk usage
        - ncdu