---
- name: "Install terminal utilities"
  hosts: all
  
  tasks:
    - name: "Install rename, jq, ncdu "
      become: yes
      apt: name= {{ item }} update_cache=yes state=latest
      with_items:
        # renaming multiple files
        - rename
        # json manipulation
        - jq
        # disk usage
        - ncdu
        # git
        - git
        
    - name: "Install glogg, lnav"
      become: yes
      apt: name= {{ item }} update_cache=yes state=latest
      with_items:
        - glogg
        - lnav

    - stat:
        path: /usr/local/bin/agrind
      register: agrind_file  

    - name: "Install angle grinder"
      shell: curl -L https://github.com/rcoh/angle-grinder/releases/download/v0.12.0/angle_grinder-v0.12.0-x86_64-unknown-linux-musl.tar.gz  | tar Ozxf -  | sudo tee /usr/local/bin/agrind > /dev/null && sudo chmod +x /usr/local/bin/agrind
      when: agrind_file.stat.exists == false
