---
- name: "Install virtual machine tools"
  hosts: all
  
  tasks:
    - name: "Install various vm tools"
      debug:
        msg : Todo  multipass

    - name: "Install Virtualbox"
      become: yes
      apt: name= {{ item }} update_cache=yes state=latest
      with_items:
        # note taking 
        - virtualbox-6.1