---
- name: "Install virtual machine tools"
  hosts: all
  become: yes
  
  vars:
    virtualbox_repo_base_url: "https://download.virtualbox.org/virtualbox"
    virtualbox_version: 6.1
    virtualbox_extpack_version: "{{ virtualbox_version}}.12"

  tasks:
    - name: "Install various vm tools"
      debug:
        msg : Todo  multipass

    - name: Add VirtualBox repo keys
      apt_key:
        url: "https://www.virtualbox.org/download/{{ item }}.asc"
        state: present
      with_items:
        - oracle_vbox
        - oracle_vbox_2016

    - name: Add VirtualBox repo
      apt_repository:
        repo: 'deb {{ virtualbox_repo_base_url }}/debian {{ ansible_distribution_release }} contrib'
        state: present
        update_cache: yes

    - name: "Install virtualbox in version {{ virtualbox_version }}"
      apt:
        name: virtualbox-{{ virtualbox_version }}
        state: present

    - name: Check if extension pack is already installed
      shell: "VBoxManage list extpacks"
      register: extpack_list

    - name: Output installed extpacks
      debug:
        var: download_result.stdtout

    - name: Download VirtualBox extension pack
      get_url:
        url: "{{ virtualbox_repo_base_url }}/{{ virtualbox_extpack_version }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_extpack_version }}.vbox-extpack"
        dest: /tmp/
        force: yes
      register: download_result
      when: 'extpack_list.stdout == "Extension Packs: 0"'

    - name: Output downloaded VirtualBox extension pack file name
      debug:
        var: download_result.dest
        verbosity: 1

    - name: Install VirtualBox extension pack
      shell: "echo 'y' | VBoxManage extpack install --replace {{ download_result.dest }}"
      when: 'extpack_list.stdout == "Extension Packs: 0"'